### PR TITLE
Add Ocarina of Time title

### PR DESCRIPTION
**Pull request by cyhyraethz**

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks! Looks a bit blurry, so I'll do another export. Thanks a lot!!!

**Comment by RobLoach** [comment]
Eh, it's pretty good. Can't get really good with DS :-P

**Comment by cyhyraethz** [comment]
I have a higher resolution version of the image (800x480) if you want to use it. I actually shrank it in order to match the other title in the database.

**Comment by RobLoach** [comment]
If you push another up that looks better, always want good ones!!!! If you use a image program to scale to 512px width, then that'd be perfect.

**Pull request merged**
