### PR TITLE
Added boxart, snaps, titles

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
When the Titles have both the game title and the screen below, it does look a bit odd when viewing a whole bunch of titles in a row... I'm okay with this though, curious what others think! :shrug: 

%20(En%2CJa%2CFr%2CDe%2CEs%2CIt%2CZh%2CKo).png)

**Comment by ghost** [comment]
Possible to get a merge for this? Thank you. @MarcoEstevez

**Comment by MarcoEstevez** [comment]
Looks good to me!

Personally like the 2 screen approach more, If there are no objections I'm willing to merge it

**Comment by RobLoach** [comment]
Sounds good with me!

**Pull request merged**
