### PR TITLE
delete symlinks

### PR DESCRIPTION
**Pull request by gerad-not-edgar**
these are all the symlinks. i have the revised files saved so they can be easily re-added as regular pngs after this is merged. as far as i know, this isnt a "symlinks created incorrectly" issue but rather a "github cannot replace symlinks correctly" issue.

### CODE REVIEW

**Review by RobLoach — CHANGES_REQUESTED** [review]
What? Symlinks work.

**Comment by i30817** [comment]
It's not github, or git; it's the github desktop application (or the electron - i think - app you can run if you press '.' on a repository which is the same codebase).

If you try to replace a symlink by a normal file with it, it creates a bugged file representation where the file exists in the repository but it's still marked as a symlink; then breaks when you pull it while not having the file (you can repair them with git reset, it seems the 'transformation to symlink' only happens when you pull).

I opened this bug about it, no comment: https://github.com/desktop/desktop/issues/14937

The ps1 symlinks in the thumbnail server were still broken¹ last time i checked because of this during some recent commits (although a PR to fix them was already merged, just waiting for updates). It's probably not the only example.


¹ https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Snaps/ search for the tomb raider files in that link and see the files with size of 8 bytes.

**Comment by i30817** [comment]
That said, this PR is just removing the symlinks without replacing them, that's not right either. And the image you added isn't resized to 512 width like the guidelines say to do.

@gerad-not-edgar , i think you can do this all at once even in the github desktop application; if you first delete the symlinks in a commit, then add their names again with copies from the file that is already there in another commit (replacing that file is not necessary, and if it's going to happen, should have width that is recommended).

PRs can have more than one commit, so doing it that way may avoid the bug, because the file wouldn't 'exist' so there is nothing to confuse with a symlink in the second commit, and that way, reverting is easier if necessary (revert the merge commit).

in the future, to make your life easier, i also recommend clicking the button to update from upstream on your github fork, then branching to a new branch first thing on the app (i noticed your PR is in :master).

**Comment by gerad-not-edgar** [comment]
I've tried removing the files, committing, then adding it all in the same pr and it doesn't work. That's why I was trying just deleting them completely, merging, then adding back as files and merging. Did you have luck with this method?

This issue isn't exclusive to the desktop application, it happens in web as well. (hence the pokemon image I shared in issue #113) 

The image I "added" was already there and I just cropped the extra white part out; it doesn't make me any difference. (I'd rather just have it cropped and be slightly smaller than resize and have it look worse)

If @RobLoach is fine with these existing as symlinks and not currently being broken, and fine with them causing issues later, I can just cancel this. It was a test to see what happens and to re-visit this topic, and try to set some rules going forward so it's not creating extra work for anyone. I don't like that the symlinks are deterring people from committing, and it has prevented me from keeping alternate versions of Pikmin 1 on Wii in particular.

**Comment by gerad-not-edgar** [comment]
These were deleted via desktop app. It makes it easier/faster to see the symlinks. let me try adding the files again so we can see what happens.

**Comment by i30817** [comment]
@RobLoach If the symlinks are necessary (because github limits the space or because you want a reliable way to make sure people use the same image for variants) then we should be careful to specify not to use the github app/desktop to replace symlinks by files until this bug is fixed.

**Comment by gerad-not-edgar** [comment]
I thought it looked good, but nope: 
image

**Comment by i30817** [comment]
Those two zelda games weren't deleted in the first commit, so it was 'just' a mistake.

https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_3DS/pull/45/commits/b1f0c282142bd3cff9daba478b6e9c8251d9e6b7

**Comment by gerad-not-edgar** [comment]
Haha. You're right 😅 missed a couple

**Comment by i30817** [comment]
You probably should close this pr and try again from a clean branch. Otherwise you need to add another two commits for the zelda games, one to delete, the other to add for a total of 4 commits.

Don't forget about the width.

**Comment by gerad-not-edgar** [comment]
Yeah, that's what I normally do. I'll close this one for now but not make another until we can decide what Rob wants to do with symlinks in general.

**Pull request closed without merging**
